version: "3.8"

services:
  frontend:
    build:
      context: web
    container_name: web
    ports:
      - "3000:3000"
    volumes:
      - ./web/app:/app/app
    restart: unless-stopped

  api:
    build:
      context: api
    container_name: api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    env_file:
      - .env
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    restart: unless-stopped
