global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'alerts.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'carbon_exporter'
    static_configs:
      - targets: ['carbon_exporter:9110']

  - job_name: 'api'
    static_configs:
      - targets: ['api:5000']

  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3020']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'
